name: Build Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Signed APK
    runs-on: ubuntu-latest
    env:
      name: 'production'
      app: 'Firebug'
      version: '1.0.0'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'firebug_keystore.jks'
          fileDir: '/home/runner/work/${{ env.app }}/${{ env.app }}/app/keystore/'
          encodedString: ${{ secrets.SIGNING_KEY }}

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Build and Sign APK
        run: ./gradlew :app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

  #      - name: Verify Signature
  #        run: $ANDROID_SDK_ROOT/build-tools/33.0.1/apksigner verify --print-certs app/build/outputs/apk/release/${{ env.app }}_${{ env.version }}.apk

  #      - name: Upload APK
  #        uses: actions/upload-artifact@v3.1.2
  #        with:
  #          name: ${{ env.app }}
  #          path: app/build/outputs/apk/release/${{ env.app }}_${{ env.version }}.apk

  unit-tests:
    name: Tests
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup JAVA 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Run Unit Test
        run: ./gradlew test

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
